#!/usr/bin/env bash
################################################################################
#
# Tests for __cache_output (bashrc), which caches the shell code generated by
# tools like fzf or zoxide, with a stand-in command in a temporary directory.
#
# Usage: tools/test-cache.sh [path/to/bash]
#
################################################################################

set -uo pipefail

BASH_BIN=${1:-bash}
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# shellcheck disable=SC2016
echo "== $("$BASH_BIN" -c 'echo "bash $BASH_VERSION"') on $(uname -s)"

mkdir -p "$work/bin"

# All cases run in one shell, so that the hash table behaves as in bashrc.
# 'fake' prints shell code: echo <version>:<arguments>
# shellcheck disable=SC2016
WORK=$work REPO=$REPO "$BASH_BIN" --norc -c '
	eval "$(sed -n "/^function __cache_output/,/^}/p" "$REPO/bashrc")"
	BASH_CACHE=$WORK/cache
	PATH=$WORK/bin:$PATH
	status=0

	make_fake() {    # make_fake VERSION [MTIME]: (re)write the stand-in command
		printf "#!/bin/sh\necho \"echo %s:\$*\"\n" "$1" > "$WORK/bin/fake"
		chmod +x "$WORK/bin/fake"
		[ -n "${2:-}" ] && touch -d "$2" "$WORK/bin/fake"
		hash -r
	}
	run() {     # run NAME ARGS...: what the cached code prints
		__cache_output "$1" fake "${@:2}" && . "$__cache_file"
	}
	check() {   # check NAME EXPECTED ACTUAL
		if [[ $3 == "$2" ]]; then
			echo "ok   $1"
		else
			echo "FAIL $1: expected \"$2\", got \"$3\""
			status=1
		fi
	}

	make_fake v1 "2000-01-01"
	check "created on first use"            "v1:a" "$(run tool a)"

	make_fake v2 "2000-01-01"
	check "cache hit (command unchanged)"   "v1:a" "$(run tool a)"

	check "regenerated when the arguments change" "v2:b" "$(run tool b)"

	make_fake v3
	touch -d "@$(( $(date +%s) + 60 ))" "$WORK/bin/fake"
	check "regenerated when the command is newer" "v3:b" "$(run tool b)"

	make_fake v4 "2000-01-01"
	sed -i "1s/^# [0-9]*/# 1000/" "$BASH_CACHE/tool.bash"
	check "regenerated after a week"        "v4:b" "$(run tool b)"

	__cache_output other nosuchcommand_xyz 2> /dev/null
	check "missing command returns 1"       "1" "$?"

	__cache_output failing false
	check "failing command returns 1"       "1" "$?"
	check "failing command leaves no cache" "no" "$([[ -e $BASH_CACHE/failing.bash ]] && echo yes || echo no)"

	(( status == 0 )) && echo "OK"
	exit $status
'
